import type { Metadata } from 'next';
import { Plus_Jakarta_Sans } from 'next/font/google';

import './globals.css';

const plusJakartaSans = Plus_Jakarta_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${plusJakartaSans.className} flex h-screen justify-center bg-gradient-to-br from-[#2C3E50] to-[#BDC3C7]`}
      >
        <main className='w-full max-w-screen-sm'>{children}</main>
      </body>
    </html>
  );
}
